version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: webphim_clickhouse
    restart: always
    environment:
      CLICKHOUSE_DB: web_phim
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default_password
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    #deploy:
    #  resources:
    #    limits:
    #      memory: 1.5G
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 60s

  fastapi-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webphim_fastapi
    restart: always
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_DB: web_phim
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default_password
      BATCH_SIZE: 50
      FLUSH_INTERVAL_SECONDS: 5
      GEMINI_API_KEY: ${GEMINI_API_KEY}

    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

    depends_on:
      clickhouse:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 500M

volumes:
  clickhouse_data:
    driver: local
